### ISSUE TITLE
Multiple commands produce 

### ISSUE THREAD

**Issue by MohammadMirzakhaniDehkordi** [farhad1985/PersianDatePicker#10]
I updated my Xcode to 9 and i got this issues, do you know how can i solve it ?
 

> :-1: Multiple commands produce '/Users/RightelVAS2/Library/Developer/Xcode/DerivedData/Ri-Navaz-gsflgcvxxcpiavbttottrkgyvgfa/Build/Products/Debug-iphonesimulator/PersianDatePicker/PersianDatePicker.framework/Info.plist':
> 1) Target 'PersianDatePicker' (project 'Pods') has copy command from '/Users/RightelVAS2/Documents/Projects/iOS/Ri-Navaz/Pods/PersianDatePicker/PersianDatePicker/Info.plist' to '/Users/RightelVAS2/Library/Developer/Xcode/DerivedData/Ri-Navaz-gsflgcvxxcpiavbttottrkgyvgfa/Build/Products/Debug-iphonesimulator/PersianDatePicker/PersianDatePicker.framework/Info.plist'
> 2) Target 'PersianDatePicker' (project 'Pods') has process command with output '/Users/RightelVAS2/Library/Developer/Xcode/DerivedData/Ri-Navaz-gsflgcvxxcpiavbttottrkgyvgfa/Build/Products/Debug-iphonesimulator/PersianDatePicker/PersianDatePicker.framework/Info.plist'
>

**Comment by farhad1985** [comment]
please clean your project . press shift +  option + command + k and after that build your project

if dont work it, close your xcode and open your terminal and enter this command

rm -rf /Users/RightelVAS2/Library/Developer/Xcode/DerivedData/Ri-Navaz-gsflgcvxxcpiavbttottrkgyvgfa

and build your project

**Comment by Mohammad2416** [comment]
Thanks for your answer, I did all of them, but those solution didn't work for me

**Comment by farhad1985** [comment]
I think it likes your problem

https://github.com/gali8/Tesseract-OCR-iOS/issues/375

**Comment by amirfahmideh** [comment]
same issue for me on Xcode 10.1

**Comment by farhad1985** [comment]
ok. I found it . in Xcode 10, I have to remove info.plist file in my lib, because it makes a conflict with your project.

**Comment by farhad1985** [comment]
please update your pod. fix it

**Comment by Negar-K** [comment]
I updated my pod. but info.plist exist yet. please fix it
