### ISSUE TITLE
Multiple commands produce at Xcode10

### ISSUE THREAD

**Issue by Fridday** [farhad1985/PersianDatePicker#11]
**Error: Multiple commands produce**

project clean and removing the folder do not work. Still get this error.

**Comment by farhad1985** [comment]
I run on iphone se with ios 12. there is no problem.
please clean with shift + option + command + k

if dont work remove in

~/Library/Developer/Xcode/DerivedData/

**Comment by Fridday** [comment]
XCODE 10:
I did what you suggested. Still does not work. (same error)

**Comment by farhad1985** [comment]
you open xcode and go to ( file > workspace settings) and change value build system to "Legacy build system" and build again.
