### ISSUE TITLE
current date problem

### ISSUE THREAD

**Issue by atriatech94** [farhad1985/PersianDatePicker#4]
current date not set until call onchange method

temporary solved by this change : 

 public func gotoCurrentDate() {	
        let currentDate = persianDateDataSource.todayCompononents()
        setDatePicker(year: currentDate.year, month: currentDate.month, day: currentDate.day)
        year = currentDate.year
        month = currentDate.month
        day = currentDate.day
        
        
    }

**Comment by farhad1985** [comment]
if you want to use the PersianDatePicker , you have to implement onChange method
