### ISSUE TITLE
defult value problem

### ISSUE THREAD

**Issue by a1malek** [farhad1985/PersianDatePicker#5]
public func gotoCurrentDate() {	
        let currentDate = persianDateDataSource.todayCompononents()
        setDatePicker(year: currentDate.year, month: currentDate.month, day: currentDate.day)
        self.year = currentDate.year
        self.month = currentDate.month
        self.day = currentDate.day
        
    }

**Comment by farhad1985** [comment]
hi!
what's the matter?
