### ISSUE TITLE
few bug or problem in this library

### ISSUE THREAD

**Issue by M0TRIX** [farhad1985/PersianDatePicker#6]
hey farhad.

street to problems 

1: how i can change to position of calender?

 let persianDatePicker = PersianDatePickerView(frame: CGRect(x: 100, y: 200, width: 200, height: 200))
        titleOfGood.inputView = persianDatePicker

this code is not changing. 

2 : how can i hide it?with out clicking on other textFilds ? i need to hide or remove it when i want

3 : how can i show the cureent year and after not past years ??

**Comment by farhad1985** [comment]
hi
I wrote a guide in readme.md
you must set onChange method . that's easy . please read my guide
