### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by rasoulmiri** [farhad1985/PersianDatePicker#7]
check this:
file:///...News/UI/News.storyboard: error: IB Designables: Failed to render and update auto layout status for NewsViewController (Atl-5G-2vg): dlopen(PersianDatePicker.framework, 1): no suitable image found.  Did find:
	PersianDatePicker.framework: required code signature missing for 'PersianDatePicker.framework'

**Comment by farhad1985** [comment]
do you use it in the storyboard ?

**Comment by rasoulmiri** [comment]
yes

**Comment by farhad1985** [comment]
you must change module in custom class to "PersianDatePicker"

**Comment by rasoulmiri** [comment]
<img width="256" alt="screen shot 2018-07-03 at 11 00 19 pm" src="https://user-images.githubusercontent.com/11883977/42238077-f44302ca-7f14-11e8-937f-0cfd07d2e5d0.png">
It has a problem :(

**Comment by farhad1985** [comment]
I tested . there is no problem. you can run my example in the project. please clean your project.
