### ISSUE TITLE
how can i set a date to calander?

### ISSUE THREAD

**Issue by M0TRIX** [farhad1985/PersianDatePicker#9]
your example is using device date but i need different date set manually

i get the date from my server
how can i do that ?

@farhad1985

**Comment by farhad1985** [comment]
Hi 
u can use of this method

 gotoDate(date: Date())

**Comment by M0TRIX** [comment]
i need not showing previous date.do you think it is possible to add this feature to your library ?
@farhad1985

**Comment by farhad1985** [comment]
in this method you can enter your date .

gotoDate(date:  your_date)

**Comment by M0TRIX** [comment]
this method goes to my favorite date but i can see previous date too
@farhad1985
